# Site settings
title: Open Source at SciLifeLab
email: robin.andeer@scilifelab.se
description: >
  A curated list of useful and actively maintained projects at
  SciLifeLab. You can find code ranging from simple bioinformatics
  resources and general programming tools right through to complete
  data analysis pipelines.
baseurl: ""
url: "http://opensource.scilifelab.se"

# Google Analytics
ga_id: "UA-18017148-9"
ga_host: "scilifelab.se"

# Build settings
environment: production
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass
